"""add updated_by_telegram_id

Revision ID: 46324ab7df9a
Revises: 5289f6ccfa3a
Create Date: 2026-02-22 16:56:46.010418
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46324ab7df9a'
down_revision = '5289f6ccfa3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_entries', sa.Column('updated_by_telegram_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_cash_entries_updated_by_telegram_id'), 'cash_entries', ['updated_by_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_entries_updated_by_telegram_id'), table_name='cash_entries')
    op.drop_column('cash_entries', 'updated_by_telegram_id')
    # ### end Alembic commands ###
