"""add_deleted_at_to_cash_entries

Revision ID: bf5111584636
Revises: 0003_cash_entries_constraints
Create Date: 2026-02-22 12:59:52.453856
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5111584636'
down_revision = '0003_cash_entries_constraints'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_cash_entries_created_by_telegram_id'), 'cash_entries', ['created_by_telegram_id'], unique=False)
    op.create_index(op.f('ix_cash_entries_deleted_at'), 'cash_entries', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('uq_currencies_code'), 'currencies', type_='unique')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_currencies_code'), 'currencies', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cash_entries_deleted_at'), table_name='cash_entries')
    op.drop_index(op.f('ix_cash_entries_created_by_telegram_id'), table_name='cash_entries')
    op.drop_column('cash_entries', 'deleted_at')
    # ### end Alembic commands ###
